### ISSUE TITLE
Feed - Visual implementation for displaying multiple comments on post

### ISSUE THREAD

**Issue by vihucode** [kitsain/Kitsain-Frontend-Spring-2024#10]
Parent US: #2 

Parent implementation: #11 

Implementation for displaying multiple comments on post. Think some smart solution how many comment is visible by default when post have x amount of comments. Rest of the comments should be possible to view by pressing comment section or icon.

**Comment by katkarin** [comment]
Currently, the user is able to view the total amount of comments posted to the post on the feed. You can see all of the comments by pressing the icon.

No preview of (for example most recent) comments has been implemented. Th.is could be implemented later if necessary.
