### ISSUE TITLE
Feed - Implementation for deleting comment by pressing it long

### ISSUE THREAD

**Issue by vihucode** [kitsain/Kitsain-Frontend-Spring-2024#12]
Parent US: #2 

Parent implementations: #11 #10 

User should be able to press own comment long to delete it. Pressing comment long should tricker pop-up/alert window where app ask if user wants to delete comment. Maybe content of the comment should be visible in pop-up/alert window?

**Comment by katkarin** [comment]
User identity check needs to be added. Currently the comments can be deleted by anyone.
