### ISSUE TITLE
Connect comment feature with backend

### ISSUE THREAD

**Issue by vihucode** [kitsain/Kitsain-Frontend-Spring-2024#26]
Parent US: #18 
Parent tasks: #28 #21 #22 

New comments are added to the backend and also feed is updated after that.

**Comment by katkarin** [comment]
Comments now connected to backend. Still needs following functionalities:
- display unique identifiers for users -> assign a number based on order of posting
- Fix bug when comments are loaded -> topmost comment displays latest comment
